const SERVER_URL = "http://localhost:5000"

const MENTOR_FORM_ROUTE = "/become-a-mentor"
const COMPENY_MENTORSHIP_ROUTE = "/start-company-mentorship"
const ROUTES = [MENTOR_FORM_ROUTE, COMPENY_MENTORSHIP_ROUTE]

export {SERVER_URL, MENTOR_FORM_ROUTE, COMPENY_MENTORSHIP_ROUTE, ROUTES}